# Generated by Django 5.1.2 on 2024-11-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stockindex_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockindex',
            name='url',
            field=models.URLField(max_length=100),
        ),
    ]
