# Generated by Django 5.1.2 on 2024-11-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_stockindex_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockindex',
            name='url',
            field=models.CharField(max_length=2048),
        ),
    ]
